version: "3.8"

services:

    ####################################################
    # JAIME
    ####################################################
    
    jaime:
        image: brianwolf94/jaime:0.12.0
        volumes: 
            - jaime:/root/.jaime
            - shared:/data:rw
        ports:
            - 5000:80
        networks: 
            - jaime-net
            
    agent1:
        image: brianwolf94/jaime-agent:0.11.0
        environment:
            - JAIME_URL=http://jaime:80
        volumes: 
            - jaime-agent:/root/.jaime-agent
            - shared:/data:rw
        ports:
            - 7001:80
        networks: 
            - jaime-net
            
    agent2:
        image: brianwolf94/jaime-agent:0.11.0
        environment:
            - JAIME_URL=http://jaime:80
        volumes: 
            - jaime-agent:/root/.jaime-agent
            - shared:/data:rw
        ports:
            - 7002:80
        networks: 
            - jaime-net
            
    front:
        image: brianwolf94/jaime-front:0.11.0
        environment:
            - JAIME_HOST=jaime
            - JAIME_PORT=80
        ports:
            - 4200:80
        networks: 
            - jaime-net
    
    ####################################################
    # TOOLS
    ####################################################
    
    dozzle:
        image: amir20/dozzle
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8081:8080
        networks: 
            - jaime-net

    filebrowser:
        image: hurlenko/filebrowser
        volumes: 
            - shared:/data:rw
            - shared:/config:rw
        ports:
            - 8080:8080
        networks: 
            - jaime-net            
            
            
volumes:
    jaime:
        external: false
    jaime-agent:
        external: false
    shared:
        external: false

        
networks:
    jaime-net:
        name: jaime-net
        external: false
