version: "3.8"

services:

    jaime:
        image: brianwolf94/jaime:0.1.1
        restart: on-failure:3
        environment:
          - LOGS_LEVEL=INFO
          - LOGS_BACKUPS=3
          - AGENTS_HTTPS=false
        volumes:
            - jaime:/root/.jaime:rw
        networks:
            - docker-net
        ports:
            - 5000:80

    agent:
        image: brianwolf94/jaime-agent:0.1.1
        restart: on-failure:3
        environment:
          - LOGS_LEVEL=INFO
          - LOGS_BACKUPS=3
          - AGENT_TYPE=OC
          - JAIME_URL=http://jaime:80
        volumes:
            - agent:/root/.jaime-agent:rw
        networks:
            - docker-net
        ports:
            - 7000:80

    dozzle:
        image: amir20/dozzle
        restart: on-failure:3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - docker-net
        ports:
            - 8080:8080

networks:
    docker-net:
        name: docker-net
        external: false

volumes:
    jaime:
        external: false
    agent:
        external: false
