version: "3.8"

services:

    ####################################################
    # JAIME
    ####################################################

    jaime:
        container_name: jaime
        image: brianwolf94/jaime:1.0.0
        volumes:
            - jaime:/root/.jaime
            - shared:/data:rw
        ports:
            - 5000:80
        networks:
            - jaime-net

    agent1:
        container_name: jaime-agent1
        image: brianwolf94/jaime-agent:1.0.0
        environment:
            - JAIME_URL=http://jaime:80
        volumes:
            - shared:/data:rw
        ports:
            - 7001:80
        networks:
            - jaime-net

    agent2:
        container_name: jaime-agent2
        image: brianwolf94/jaime-agent:1.0.0
        environment:
            - JAIME_URL=http://jaime:80
        volumes:
            - shared:/data:rw
        ports:
            - 7002:80
        networks:
            - jaime-net

    front:
        container_name: jaime-front
        image: brianwolf94/jaime-front:1.0.0
        environment:
            - JAIME_HOST=jaime
            - JAIME_PORT=80
        ports:
            - 4200:80
        networks:
            - jaime-net

    ####################################################
    # TOOLS
    ####################################################

    dozzle:
        container_name: dozzle
        image: amir20/dozzle
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8081:8080
        networks:
            - jaime-net

    filebrowser:
        container_name: filebrowser
        image: hurlenko/filebrowser
        volumes:
            - shared:/data:rw
            - shared:/config:rw
        ports:
            - 8080:8080
        networks:
            - jaime-net

volumes:
    jaime:
        external: false
    jaime-agent:
        external: false
    shared:
        external: false

networks:
    jaime-net:
        name: jaime-net
        external: false
